version: '3'
services:
  api:
    build: .
    networks:
      - mango-backend
    restart: 'always'
    ports:
      - 8000:8000
    environment:
      - API_PROXY_HOST
      - API_ROOT_PATH
      - API_ENABLE_SSL
      - SOURCE_DATA_ROOT
      - LOGS_ROOT=/logs
      - TSDB_HOST
      - TSDB_PORT
      - TSDB_PASSWORD=${DB_PASSWORD}
    volumes:
      - $LOGS_ROOT:/logs
      - $SOURCE_DATA_ROOT:/input
      - $SSL_CERTS_PATH:/certs
    user: root
    command: conda run -n masschange /app/masschange/start_api.sh
  db:
    user: "${MANGO_UID}:${MANGO_GID}"
    image: 'timescale/timescaledb-ha:pg16'
    networks:
      - mango-backend
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - $PERSIST_LOCATION:/home/postgres/pgdata/data
  ingest-crawler:
    build: .
    networks:
      - mango-backend
    restart: 'always'
    environment:
      - SOURCE_DATA_ROOT
      - LOGS_ROOT=/logs
      - TSDB_HOST
      - TSDB_PORT
      - TSDB_PASSWORD=${DB_PASSWORD}
    volumes:
      - $LOGS_ROOT:/logs
      - $SOURCE_DATA_ROOT:/input
      - $INGEST_STAGING_ROOT:/staging
    user: root
    command: conda run -n masschange python /app/masschange/src/masschange/ingest/crawler/main.py --src /input --dest /staging --remove-src-files --loop
  ingest-worker:
    build: .
    networks:
      - mango-backend
    restart: 'always'
    environment:
      - SOURCE_DATA_ROOT
      - LOGS_ROOT=/logs
      - TSDB_HOST
      - TSDB_PORT
      - TSDB_PASSWORD=${DB_PASSWORD}
    volumes:
      - $LOGS_ROOT:/logs
      - $SOURCE_DATA_ROOT:/input
      - $INGEST_STAGING_ROOT:/staging
    user: root
    command: conda run -n masschange python /app/masschange/src/masschange/ingest/executor/main.py --loop
  ensure:
    build: .
    networks:
      - mango-backend
    environment:
      - LOGS_ROOT=/logs
      - TSDB_HOST
      - TSDB_PORT
      - TSDB_PASSWORD=${DB_PASSWORD}
      - LOGS_ROOT=/logs
    volumes:
      - $LOGS_ROOT:/logs
    user: root
    command: conda run -n masschange python /app/masschange/src/masschange/db/ensure.py

networks:
  mango-backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
    driver_opts:
      com.docker.network.bridge.name: 'mango-backend'
