name: masschange
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
# Jupyter Lab
#  - jupyterlab=3.5.2
## Python scientific libraries
  - numpy=1.25.0
  - pandas=2.0.0
#  - scipy=1.10.0
#  - scikit-image=0.19.3
#  - matplotlib=3.6.2
#  - xarray=2022.12.0
#  - beautifulsoup4=4.11.1
#  - pyinstaller
## Geospatial libraries
#  - rasterio=1.3.4
#  - gdal=3.6.2
#  - geopandas=0.12.2
#  - rioxarray=0.13.3
#  - geocube=0.3.3
#  - earthpy=0.9.4
#  - ipyleaflet=0.17.2
#  - rasterstats=0.17.0
#  - netcdf4=1.6.2
#  - fiona=1.8.22  # 1.9.0 introduced breaking change
  - pip:
#    - ./src
    - lttb==0.3.1
    - lttbc==0.2.4
    - pyarrow==12.0.1
    - pyspark==3.4.1
    - fastapi[all]==0.100.0
    - uvicorn==0.23.1
#    - fastapi-utils==0.2.1  # conflicts with pydantic>=2, which is required for latest fastapi
    - pytest
