name: masschange
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.25.0
  - pandas=2.0.0
  - pip:
#    - ./src
    - fastapi[all]==0.100.0
    - uvicorn==0.23.1
#    - fastapi-utils==0.2.1  # conflicts with pydantic>=2, which is required for latest fastapi
    - psycopg2==2.9.9
    - pytest
    - StrEnum==0.4.15
